AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Template to deploy a URL shortener app with SAM on AWS'
Globals:
  Function:
      Runtime: python3.7
      MemorySize: 3008
      CodeUri: ./lambda
      Environment:
        Variables:
          TABLE_NAME: UrlShortener-LinkTable
          PRIMARY_KEY: ShortUrl
          POINTS_TO: Link
Resources:
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: This lambda lists all of the urls that have been added
      FunctionName: UrlShortener-ListFunction
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName:
              UrlShortener-LinkTable
      Events:
        ApiEvent:
          Properties:
            Method: get
            Path: /list-all
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: list.lambda_handler
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: This lambda creates the url and puts it in the database
      FunctionName: UrlShortener-CreateFunction
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName:
              UrlShortener-LinkTable
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /{name}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: create.lambda_handler
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener
  CreateFunctionTheSecond:
    Type: AWS::Serverless::Function
    Properties:
      Description: This lambda creates the url and puts it in the database
      FunctionName: UrlShortener-CreateFunctionTheSecond
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName:
              UrlShortener-LinkTable
      Events:
        ApiEvent:
          Properties:
            Method: post
            Path: /
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: create.lambda_handler
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener    
  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: This lambda returns the url that the url points to
      FunctionName: UrlShortener-SearchFunction
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName:
              UrlShortener-LinkTable
      Events:
        ApiEvent:
          Properties:
            Method: get
            Path: /{name}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: search.lambda_handler
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: UrlApi
      EndpointConfiguration: EDGE
      Cors: "'*'"
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener
  TableThing:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ShortUrl
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: UrlShortener-LinkTable
      Tags:
        Author: Matthew Williams
        ProjectName: UrlShortener